"""
Generate a self-contained HTML report from an AutoFitReport.
No external dependencies — pure Python stdlib + inline SVG/CSS.
"""
from __future__ import annotations

import json
import math
import html as _html
from datetime import datetime


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate(report, csv_source: str, n_total: int) -> str:
    is_regression = report.scoring_metric == "neg_mse"
    metric_label  = "RMSE" if is_regression else report.scoring_metric
    lower_better  = " &nbsp;·&nbsp; lower = better" if is_regression else ""

    def fmt(raw):
        if raw is None or raw != raw:
            return "N/A"
        return f"{math.sqrt(abs(raw)):.4f}" if is_regression else f"{raw:.4f}"

    best_score_str = fmt(report.best_score)
    sampled_note   = f"{report.n_rows:,} / {n_total:,}" if report.n_rows < n_total else f"{n_total:,}"
    timestamp      = datetime.now().strftime("%Y-%m-%d %H:%M")

    # ------------------------------------------------------------------ #
    # Sections                                                             #
    # ------------------------------------------------------------------ #
    rankings_html = _rankings_table(report, fmt, metric_label)
    chart_html    = _importance_chart(report.feature_importances[:10] if report.feature_importances else [])
    params_html   = _params_section(report)
    warnings_html = _warnings_section(report.warnings)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GlassBox — {_e(report.target_column)}</title>
<style>
{_CSS}
</style>
</head>
<body>

<header>
  <div class="header-inner">
    <div class="logo">GlassBox AutoFit</div>
    <h1>Predicting <span class="target-pill">{_e(report.target_column)}</span></h1>
    <p class="subtitle">
      {_e(csv_source)} &nbsp;·&nbsp;
      {_e(report.task_type.title())} &nbsp;·&nbsp;
      {sampled_note} rows &nbsp;·&nbsp;
      {timestamp}
    </p>
  </div>
</header>

<main>

  <!-- Summary row -->
  <div class="card">
    <h2>Summary</h2>
    <div class="stat-grid">
      <div class="stat">
        <div class="stat-val">{_e(report.best_model)}</div>
        <div class="stat-lbl">Best Model</div>
      </div>
      <div class="stat">
        <div class="stat-val">{best_score_str}</div>
        <div class="stat-lbl">CV {_e(metric_label)}{lower_better}</div>
      </div>
      <div class="stat">
        <div class="stat-val">{report.n_rows:,}</div>
        <div class="stat-lbl">Rows used</div>
      </div>
      <div class="stat">
        <div class="stat-val">{report.n_features_in}</div>
        <div class="stat-lbl">Input features</div>
      </div>
      <div class="stat">
        <div class="stat-val">{report.elapsed_seconds:.1f}s</div>
        <div class="stat-lbl">Search time</div>
      </div>
    </div>
  </div>

  <!-- Model rankings -->
  <div class="card">
    <h2>Model Rankings</h2>
    {rankings_html}
  </div>

  <!-- Feature importances -->
  {"<div class='card'><h2>Top Features</h2>" + chart_html + "</div>" if chart_html else ""}

  <!-- Best hyperparameters -->
  {params_html}

  <!-- Warnings -->
  {warnings_html}

</main>

<footer>Generated by GlassBox AutoFit &nbsp;·&nbsp; {timestamp}</footer>

</body>
</html>"""


# ---------------------------------------------------------------------------
# HTML fragments
# ---------------------------------------------------------------------------

def _rankings_table(report, fmt, metric_label: str) -> str:
    rows = ""
    for r in report.model_rankings:
        is_best = r["model"] == report.best_model
        raw = r.get("best_score")
        sc  = fmt(raw) if raw is not None else "<span class='failed'>failed</span>"
        cls = ' class="best"' if is_best else ""
        medal = " 🥇" if is_best else ""
        rows += f"<tr{cls}><td>{_e(r['model'])}{medal}</td><td>{sc}</td></tr>\n"

    return f"""<table>
<thead><tr><th>Model</th><th>CV {_e(metric_label)}</th></tr></thead>
<tbody>{rows}</tbody>
</table>"""


def _importance_chart(features: list) -> str:
    if not features:
        return ""

    ROW_H   = 34
    GAP     = 8
    LBL_W   = 190
    BAR_MAX = 380
    VAL_W   = 60
    W       = LBL_W + BAR_MAX + VAL_W
    H       = len(features) * (ROW_H + GAP) + GAP

    max_val = max(f["importance"] for f in features) or 1.0

    # Palette: rich blue → steel blue
    COLORS = [
        "#1e3a8a","#1d4ed8","#2563eb","#3b82f6",
        "#60a5fa","#93c5fd","#a5b4fc","#c7d2fe","#ddd6fe","#ede9fe",
    ]

    svgs = []
    for i, fi in enumerate(features):
        y     = GAP + i * (ROW_H + GAP)
        w     = max(4, int((fi["importance"] / max_val) * BAR_MAX))
        color = COLORS[min(i, len(COLORS) - 1)]
        lbl   = (fi["feature"][:28] + "…") if len(fi["feature"]) > 28 else fi["feature"]
        cy    = y + ROW_H // 2 + 5

        svgs.append(f"""
  <text x="{LBL_W - 10}" y="{cy}" text-anchor="end" class="lbl">{_e(lbl)}</text>
  <rect x="{LBL_W}" y="{y}" width="{w}" height="{ROW_H}" fill="{color}" rx="5"/>
  <text x="{LBL_W + w + 8}" y="{cy}" class="val">{fi["importance"]:.4f}</text>""")

    return f"""<svg width="100%" viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg"
     style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
{"".join(svgs)}
</svg>"""


def _params_section(report) -> str:
    if not report.best_params:
        return ""
    pretty = _e(json.dumps(report.best_params, indent=2))
    return f"""<div class="card">
  <h2>Best Hyperparameters <span class="badge">{_e(report.best_model)}</span></h2>
  <pre class="code">{pretty}</pre>
</div>"""


def _warnings_section(warnings: list) -> str:
    if not warnings:
        return ""
    items = "".join(f"<div class='warn-item'>⚠️ {_e(w)}</div>" for w in warnings)
    return f'<div class="card"><h2>Warnings</h2>{items}</div>'


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _e(s) -> str:
    return _html.escape(str(s))


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f1f5f9;
  color: #1e293b;
  min-height: 100vh;
}

header {
  background: linear-gradient(135deg, #0f172a 0%, #1e3a8a 60%, #1d4ed8 100%);
  color: white;
  padding: 48px 0 40px;
}
.header-inner {
  max-width: 960px;
  margin: 0 auto;
  padding: 0 28px;
}
.logo {
  font-size: 0.8em;
  font-weight: 700;
  letter-spacing: 2px;
  text-transform: uppercase;
  opacity: 0.6;
  margin-bottom: 12px;
}
header h1 {
  font-size: 2em;
  font-weight: 800;
  line-height: 1.2;
}
.target-pill {
  background: rgba(255,255,255,0.15);
  border: 1px solid rgba(255,255,255,0.3);
  padding: 2px 14px;
  border-radius: 20px;
  font-style: normal;
}
.subtitle {
  margin-top: 12px;
  opacity: 0.65;
  font-size: 0.95em;
}

main {
  max-width: 960px;
  margin: 32px auto;
  padding: 0 24px;
}

.card {
  background: white;
  border-radius: 14px;
  padding: 28px 32px;
  margin-bottom: 24px;
  box-shadow: 0 1px 4px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04);
}
.card h2 {
  font-size: 1em;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.8px;
  color: #64748b;
  margin-bottom: 22px;
}

/* Summary stats */
.stat-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 20px;
}
.stat { text-align: center; }
.stat-val {
  font-size: 1.7em;
  font-weight: 800;
  color: #1e3a8a;
  line-height: 1.1;
}
.stat-lbl {
  font-size: 0.75em;
  color: #94a3b8;
  margin-top: 5px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

/* Table */
table { width: 100%; border-collapse: collapse; }
th {
  background: #0f172a;
  color: white;
  padding: 11px 18px;
  text-align: left;
  font-size: 0.85em;
  font-weight: 600;
  letter-spacing: 0.4px;
}
th:first-child { border-radius: 8px 0 0 0; }
th:last-child  { border-radius: 0 8px 0 0; }
td {
  padding: 12px 18px;
  border-bottom: 1px solid #f1f5f9;
  font-size: 0.95em;
}
tr:last-child td { border-bottom: none; }
tr.best td      { background: #fefce8; font-weight: 700; }
tr:hover td     { background: #f8fafc; }
tr.best:hover td { background: #fef9c3; }
.failed { color: #ef4444; }

/* Badge */
.badge {
  background: #dbeafe;
  color: #1d4ed8;
  padding: 3px 12px;
  border-radius: 20px;
  font-size: 0.8em;
  font-weight: 600;
  text-transform: none;
  letter-spacing: 0;
  margin-left: 8px;
  vertical-align: middle;
}

/* Code block */
.code {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 18px;
  font-family: 'Monaco', 'Menlo', 'Courier New', monospace;
  font-size: 0.87em;
  line-height: 1.6;
  overflow-x: auto;
  white-space: pre-wrap;
  color: #334155;
}

/* SVG chart text */
.lbl { font-size: 13px; fill: #475569; }
.val { font-size: 12px; fill: #94a3b8; }

/* Warnings */
.warn-item {
  background: #fffbeb;
  border-left: 4px solid #f59e0b;
  padding: 11px 16px;
  border-radius: 0 8px 8px 0;
  margin-bottom: 8px;
  font-size: 0.9em;
  color: #78350f;
}
.warn-item:last-child { margin-bottom: 0; }

footer {
  text-align: center;
  color: #94a3b8;
  font-size: 0.8em;
  padding: 32px 0 48px;
}

@media (max-width: 600px) {
  .stat-grid { grid-template-columns: repeat(2, 1fr); }
  .card { padding: 20px; }
  header { padding: 32px 0 28px; }
}
"""
